//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrialSparePartPortal.MasterPages
{


    public partial class SiteMaster
    {

        /// <summary>
        /// head control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// navHome control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navHome;

        /// <summary>
        /// navParts control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navParts;

        /// <summary>
        /// navSuppliers control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navSuppliers;

        /// <summary>
        /// navTechnicians control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navTechnicians;

        /// <summary>
        /// navHowItWorks control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navHowItWorks;

        /// <summary>
        /// navWhyUs control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navWhyUs;

        /// <summary>
        /// navEmergency control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navEmergency;

        /// <summary>
        /// navLogin control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navLogin;

        /// <summary>
        /// navRegister control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navRegister;

        /// <summary>
        /// navMobHome control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobHome;

        /// <summary>
        /// navMobParts control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobParts;

        /// <summary>
        /// navMobSuppliers control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobSuppliers;

        /// <summary>
        /// navMobTechnicians control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobTechnicians;

        /// <summary>
        /// navMobHowItWorks control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobHowItWorks;

        /// <summary>
        /// navMobWhyUs control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobWhyUs;

        /// <summary>
        /// navMobEmergency control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor navMobEmergency;

        /// <summary>
        /// phAnonymous control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phAnonymous;

        /// <summary>
        /// phAuthenticated control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phAuthenticated;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkDashboard;

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        /// <summary>
        /// phPreFooterEmergency control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phPreFooterEmergency;

        /// <summary>
        /// ScriptsContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
